# Generated by Django 2.0.13 on 2019-06-21 08:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercise3', '0002_jounal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jounal',
            new_name='Journal',
        ),
    ]
