# Generated by Django 2.0.13 on 2019-06-21 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise3', '0005_todolist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='taskname',
            new_name='title',
        ),
    ]
