# Generated by Django 2.0.13 on 2019-06-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise3', '0006_auto_20190621_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='checkbox',
            field=models.BooleanField(default=True),
        ),
    ]
